### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wongsyrone** [wongsyrone/openwrt-1#89]
- [ ] check iproute2 v4.5 when kernel update to 4.5
- [x] nettle and gmp
- [x] moving to LEDE https://github.com/wongsyrone/lede-1
